artlounge/urls.py
from django.conf.urls import patterns, include, url

from app.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^design/$', DesignView.as_view(), name='design'),
    url(r'^mebel/$', MebelView.as_view(), name='mebel'),
    url(r'^art/$', ArtView.as_view(), name='art'),
    url(r'^order/$', OrderAjaxView.as_view(), name='order-ajax'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

app/models.py
# coding: utf-8
from django.db import models

# Create your models here.

class Order(models.Model):
    email = models.CharField(max_length=256, verbose_name=u'E-mail')
    comment = models.TextField(verbose_name=u'Комментарий')

    def __unicode__(self):
        return self.email

    class Meta:
        verbose_name = u'Заполнение формы отправки'
        verbose_name_plural = u'Заполнения формы отправки'

class MenuItem(models.Model):
    name = models.CharField(max_length=256, verbose_name=u'Название')
    text = models.TextField(verbose_name=u'Текст страницы', blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u'Разделы меню'
        verbose_name = u'Раздел меню'

class ImageItem(models.Model):
    image = models.ImageField(upload_to=u'upload/', verbose_name=u'Изображение', blank=True, null=True)
    small_image = models.ImageField(upload_to=u'upload/', verbose_name=u'Превью')
    menuitem = models.ForeignKey(MenuItem, verbose_name=u'Раздел меню')

    def __unicode__(self):
        return u'{}: {}'.format(self.menuitem.name, self.pk)

    class Meta:
        verbose_name_plural = u'Изображения'
        verbose_name = u'Изображение'

app/forms.py
from django.forms import ModelForm, TextInput
from app.models import Order
class OrderForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['comment'].widget = TextInput()
    class Meta:
        model = Order

app/views.py
# coding: utf-8
from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.http import HttpResponse
from app.models import *
from app.forms import *
from django.core.mail import send_mail
import django_settings
# Create your views here.

class GeneralMixin(object):
    def get_context_data(self, **kwargs):
        ctx = super(GeneralMixin, self).get_context_data(**kwargs)
        ctx['order_form'] = OrderForm()
        return ctx

class OrderAjaxView(View):
    def post(self, request, *args, **kwargs):
        if request.POST:
            form = OrderForm(request.POST)
            if form.is_valid():
                order = form.save()
                msg = u'E-mail: {}\nКомментарий: {}'.format(order.email, order.comment)
                send_mail(u'Заполнение формы на сайте art-lounge.ru',msg, 'info@art-lounge.ru', [django_settings.get('admin_email'),])
        return HttpResponse('OK')

class HomeView(GeneralMixin, TemplateView):
    template_name = 'home.html'

class DesignView(GeneralMixin, TemplateView):
    template_name = 'gallery.html'

    def get_context_data(self, **kwargs):
        ctx = super(DesignView, self).get_context_data(**kwargs)
        ctx['photos'] = ImageItem.objects.filter(menuitem__name=u'Дизайн и декор')
        ctx['text'] = MenuItem.objects.get(name=u'Дизайн и декор').text
        ctx['active'] = 'design'
        return ctx

class MebelView(GeneralMixin, TemplateView):
    template_name = 'gallery.html'

    def get_context_data(self, **kwargs):
        ctx = super(MebelView, self).get_context_data(**kwargs)
        ctx['photos'] = ImageItem.objects.filter(menuitem__name=u'Мебель')
        ctx['text'] = MenuItem.objects.get(name=u'Мебель').text
        ctx['active'] = 'mebel'
        return ctx

class ArtView(GeneralMixin, TemplateView):
    template_name = 'gallery.html'

    def get_context_data(self, **kwargs):
        ctx = super(ArtView, self).get_context_data(**kwargs)
        ctx['photos'] = ImageItem.objects.filter(menuitem__name=u'Искусство')
        ctx['text'] = MenuItem.objects.get(name=u'Искусство').text
        ctx['active'] = 'art'
        return ctx

templates/base.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Art Lounge</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.fancybox.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" />

</head>
<body>
<div class="top">
    <a href="/">
        <img src="{{ STATIC_URL }}img/logo.png" />
    </a>
</div>
<div class="inner">
    <div class="top-links">
        <a href="https://www.facebook.com/artloungerussia">
            <img src="{{ STATIC_URL }}img/fb-icon.jpg" />
        </a>
    </div>
    <div class="border"></div>
    <div class="big-title">
        Art.Design.Decor
    </div>
    <div class="border"></div>
</div>
{% block slider %}
    <div class="slider">
        <img src="{{ STATIC_URL }}img/banner0.jpg" />
    </div>
{% endblock %}
<div class="inner">
    <div class="menu">
        <div class="menu-item">
            <a href="{% url 'design' %}" class="{% if active == 'design' %}active{% endif %}">
                <img src="{{ STATIC_URL }}img/design-button.png" style="width: 180px; height: auto;" />
                <div class="menu-item-name">Дизайн и декор</div>
            </a>
        </div>
        <div class="menu-item">
            <a href="{% url 'mebel' %}" class="{% if active == 'mebel' %}active{% endif %}">
                <img src="{{ STATIC_URL }}img/mebel-button.png" />
                <div class="menu-item-name">Мебель</div>
            </a>
        </div>
        <div class="menu-item">
            <a href="{% url 'art' %}" class="{% if active == 'art' %}active{% endif %}">
                <img src="{{ STATIC_URL }}img/pic-button.png" />
                <div class="menu-item-name">Искусство</div>
            </a>
        </div>
    </div>
</div>
{% block content %}
<div class="inner about">
    <div class="big-title">
        О Нас
    </div>
    <div class="border"></div>
    <div class="post">
        <div class="post-images">
            <a href="{{ STATIC_URL }}img/b01.jpg" class="main-photos" rel="main">
                <img src="{{ STATIC_URL }}img/01.jpg" />
            </a>
            <a href="{{ STATIC_URL }}img/b02.jpg" class="main-photos" rel="main">
                <img src="{{ STATIC_URL }}img/02.jpg" />
            </a>
            <a href="{{ STATIC_URL }}img/b03.jpg" class="main-photos" rel="main">
                <img src="{{ STATIC_URL }}img/03.jpg" />
            </a>
            <a href="{{ STATIC_URL }}img/b04.jpg" class="main-photos" rel="main">
                <img src="{{ STATIC_URL }}img/04.jpg" />
            </a>
            <a href="{{ STATIC_URL }}img/b05.jpg" class="main-photos" rel="main">
                <img src="{{ STATIC_URL }}img/05.jpg" />
            </a>
{#            <img src="{{ STATIC_URL }}img/post-img-0.jpg" />#}
{#            <img src="{{ STATIC_URL }}img/post-img-1.jpg" />#}
{#            <img src="{{ STATIC_URL }}img/post-img-2.jpg" />#}
        </div>
        <div class="post-text">
            <div>
Создание интерьера – это щепетильная и отнюдь не простая задача, во всяком случае для тех, кто желает сделать его безупречным. Тонкий и грамотный подход является залогом успеха в данном вопросе. Интерьерный бутик "ART LOUNGE " предлагает свои услуги по созданию и усовершенствованию интерьеров.


 </div><div>
                Интерьерный бутик "ART LOUNGE " располагает к неторопливому выбору предметов и материалов для создания образа помещения. Уютная и исключительно конфиденциальная атмосфера,располагающая к отдыху и расслаблению,полному отвлечению от суеты мегаполиса и грамотный подход консультантов позволяют нашим клиентам оценить предложенные нами решения и выбрать оптимальные.

 </div><div>
За чашечкой ароматного кофе, бокалом горячительного или прохладительного напитка, Вы сможете оценить нестандартные и яркие решения индивидуально для Вашего интерьера в соответствии с Вашими приоритетами и жизненными взглядами.


 </div><div>
<b>Профессиональный подход во всем</b>


 </div><div>
Наш интерьерный бутик предоставляет следующие услуги:

 </div><div>
Создание дизайн проекта жилых и коммерческих помещений;

 </div><div>
Декорирование помещений;

 </div><div>
Авторский надзор;

 </div><div>
Эксклюзивный эко- дизайн;

 </div><div>
Дополнение свежего образа картинами, элементами текстиля и яркими акцентами;

 </div><div>
Помощь в выборе изысканной мебели.

 </div><div>
Тонкое чувство вкуса и безупречные знания о видах и проблемах интерьеров, позволяет нам создавать поистине потрясающие образы помещений. Дизайн проекты в нашем исполнении полностью соответствуют стилистическим предпочтениям клиента.

 </div><div>
 С помощью профессиональных дизайнеров нашего бутика Вы сможете успешно обновить, дополнить или полностью изменить интерьер своего дома.


 </div><div>
<b>Актуальный и современный подарок</b>

 </div><div>
Стоит ли говорить, что уникальные предметы интерьера могут стать прекрасным подарком для любого ценителя прекрасного. Интерьерный бутик "ART LOUNGE " может похвастаться многообразием интересных вещей и элементов интерьера.Среди  обилия эксклюзивных предметов можно без труда подобрать что-то для конкретного помещения и  гармонично его дополнить.

 </div><div>
 Огромный выбор живописи от известных художников приятно удивит Вас и поможет порадовать Ваших близких и дорогих людей подарком,который по-настоящему будет оценен.

 </div><div>
На представленной экспозиции можно увидеть и шикарную мебель, качество и модели которой удовлетворят вкусы даже самого требовательного и взыскательного клиента с тонким чувством вкуса.

 </div><div>
А дизайнерские элементы интерьера из натурального мха никого не оставят равнодушными.

 </div><div>
При выборе подарка многие останавливают свое внимание на необычных и редких вещах. Желание удивить своего знакомого, друга, родственника или вторую половинку наталкивает на поиск лиммитированных  и эксклюзивных вещей. Интерьерный бутик "ART LOUNGE " – это не только возможность получить профессиональную консультацию по созданию интерьера и заказать соответствующий дизайн-проект, но и возможность приобрести уникальную вещь в качестве подарка. Многообразие изделий позволяет клиенту сделать неторопливый, верный выбор.            </div>
        </div>
    </div>
    </div>
{% endblock %}
<div class="inner">
    <div class="border"></div>
    <div class="contacts">
        <div class="left">
            <div class="big-title">
                Контактная информация
            </div>
            <div class="contacts-desc">
                Мы расположены по адресу:<br/>
                195112 Санкт-Петербург, Заневский д. 4<br />
                Тел.:+7(812) 650-55-22<br/>
                Факс:+7(812) 445-16-22             <a href="#">Посмотреть на карте</a>
            </div>
            <img src="{{ STATIC_URL }}img/contacts-img.jpg" />

        </div>
        <div class="right">
            <form method="POST" id="bottom-form-id">{% csrf_token %}
                <div class="big-title">
                    Написать нам
                </div>
                <div class="contacts-desc" style="padding-top: 45px;">
                    Вы всегда сможите связатся с нами или написать нам свои пожелания
                </div>
                <div class="input-wrapper">
                    {{ order_form.email|attr:"placeholder:Ваш E-mail" }}
{#                    <input type="text" placeholder="Ваш E-mail" name="email" id="id_email" />#}
                </div>
                <div class="input-wrapper">
                    {{ order_form.comment|attr:"placeholder:Написать комментарий" }}
{#                    <input type="text" placeholder="Написать комментарий" name="comment" id="id_comment" />#}
                </div>
                <div class="input-wrapper">
                    <button type="submit">Отправить</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="footer">
    <div class="inner">
        © 2014 ARt Lounge
    </div>
</div>
<div class="message-send-modal" style="display: none;">
    <div class="big-title">Спасибо, Ваше сообщение успешно отправлено</div>
    <p>Мы скоро с вами свяжемся</p>
</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.fancybox.js"></script>
    <script src="{{ STATIC_URL }}js/common.js"></script>
</body>
</html>

templates/gallery.html
{% extends 'base.html' %}

{% block slider %}{% endblock %}

{% block content %}
    <div class="gallery">
        <div class="top-desc">
            {{ text|safe }}
        </div>
        {% for photo in photos %}
            <div class="gallery-item" rel="gallery">
                {% if photo.image %}
                <a href="{{ photo.image.url }}" rel="gallery">
                    <img src="{{ photo.small_image.url }}" />
                </a>
                {% else %}
                    <img src="{{ photo.small_image.url }}" />
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}